version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=dockeruser
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: dockeruser

volumes:
  data: {

  }